name = "PkgTest"
uuid = "06e1a388-e1fa-45d6-a1b6-f373e63792e8"
authors = ["Hasan Al-Shammari"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
